
version: '3.8'

services:
  ai:
    container_name: ai
    build:
      context: ./web/frontend/AI
      dockerfile: Dockerfile
    volumes:
      - ./web/frontend/AI:/code
    ports:
      - "8001:8001"
    networks:
      - gameplay_network
  gameplay:
    container_name: gameplay
    build:
      context: ./web/frontend/Gameplay
      dockerfile: Dockerfile
    volumes:
      - ./web/frontend/Gameplay:/code
    ports:
      - "8000:8000"
    networks:
      - gameplay_network

networks:
  gameplay_network:
    driver: bridge 

volumes:
  gameplay_data:
    driver: local
  ai_data:
    driver: local
