services:

  database:
    build:
      context: ./web/database
    image: db-sqlite:0.1
    container_name: database
    env_file: .env
    # networks:
    #   - transcendnet
    volumes:
      - shared_db_volume:/var/www/app/data
    restart: on-failure

  backend:
    build:
      context: ./web/backend
    image: backend-fastify:0.1
    container_name: backend
    env_file: .env
    networks:
      - transcendnet
    volumes:
      - ./web/backend/srcs:/app/srcs
      - ./web/backend/package.json:/app/package.json
      - backend_node_modules:/app/node_modules
      - shared_db_volume:/app/data
    ports:
      - "3000:3000"
    depends_on:
      - database
    restart: on-failure

  frontend:
    build:
      context: ./web/frontend
    image: frontend-react:0.1
    container_name: frontend
    env_file: .env
    volumes:
      - ./web/frontend/react_frontend/src:/app/src
      - ./web/frontend/react_frontend/public:/app/public

      - ./web/frontend/react_frontend/package.json:/app/package.json
      - ./web/frontend/react_frontend/package-lock.json:/app/package-lock.json

      - ./web/frontend/react_frontend/tsconfig.json:/app/tsconfig.json
      - ./web/frontend/react_frontend/tsconfig.app.json:/app/tsconfig.app.json
      - ./web/frontend/react_frontend/vite.config.ts:/app/vite.config.ts
      - frontend_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    networks:
      - transcendnet
    depends_on:
      - database
      - backend
    restart: on-failure

  ai:
    container_name: ai
    build:
      context: ./game_logic/AI
      dockerfile: Dockerfile
    volumes:
      - ./game_logic/AI:/code
    ports:
      - "8001:8001"
    networks:
      - gameplay_network
  gameplay:
    container_name: gameplay
    build:
      context: ./game_logic/Gameplay
      dockerfile: Dockerfile
    volumes:
      - ./game_logic/Gameplay:/code
    ports:
      - "8000:8000"
    networks:
      - gameplay_network

volumes:
  backend_node_modules:
    name: backend_node_modules
    driver: local
  shared_db_volume:
    name: shared_db_volume
    driver: local
  frontend_node_modules:
    name: frontend_node_modules
    driver: local
  gameplay_data:
    name: gameplay_data
    driver: local
  ai_data:
    name: ai_data
    driver: local

networks:
  transcendnet:
    name: transcendnet
    driver: bridge
  gameplay_network:
    driver: bridge 

  
