services:
  nginx:
    build:
      context: ./nginx
    image: nginx-ssl:latest
    container_name: nginx
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/ssl:ro
    ports:
      - "443:443"
    depends_on:
      - frontend
      - backend
      - gameplay
    networks:
      - transcendnet
      - netplay
  database:
    build:
      context: ./web/database
    image: db-sqlite:0.1
    container_name: database
    env_file: .env
    networks:
      - transcendnet
    volumes:
      - shared_db_volume:/var/www/app/data
    restart: on-failure

  backend:
    build:
      context: ./web/backend
    image: backend-fastify:0.1
    container_name: backend
    env_file: .env
    networks:
      - transcendnet
    volumes:
      - ./web/backend/srcs:/app/srcs
      - ./web/backend/package.json:/app/package.json
      - backend_node_modules:/app/node_modules
      - ./web/backend/data:/app/data
    expose:
      - "3000"
    depends_on:
      - database
    restart: on-failure

  frontend:
    build:
      context: ./web/frontend
    image: frontend-ts:0.1
    container_name: frontend
    env_file: .env
    volumes:
      - ./web/frontend/ts_frontend/src:/app/src
      - ./web/frontend/ts_frontend/public:/app/public
      - ./web/frontend/ts_frontend/package.json:/app/package.json
      - ./web/frontend/ts_frontend/package-lock.json:/app/package-lock.json
      - ./web/frontend/ts_frontend/tsconfig.json:/app/tsconfig.json
      - ./web/frontend/ts_frontend/vite.config.ts:/app/vite.config.ts
      - ./web/frontend/ts_frontend/index.html:/app/index.html
      - frontend_node_modules:/app/node_modules
    expose:
      - "5173"
    networks:
      - transcendnet
    depends_on:
      - database
      - backend
    restart: on-failure

  gameplay:
    container_name: gameplay
    build:
      context: ./game_logic/Gameplay
      dockerfile: Dockerfile
    volumes:
      - ./game_logic/Gameplay:/code
    expose:
      - "8000"
    networks:
      - netplay
    restart: on-failure
  ai:
    container_name: ai
    build:
      context: ./game_logic/AI
      dockerfile: Dockerfile
    volumes:
      - ./game_logic/AI:/code
      - ai_data:/code/data
    expose:
      - "8001"
    depends_on:
      - gameplay
    networks:
      - netplay
    restart: on-failure
  

volumes:
  backend_node_modules:
    name: backend_node_modules
    driver: local
  shared_db_volume:
    name: shared_db_volume
    driver: local
  frontend_node_modules:
    name: frontend_node_modules
    driver: local
  ai_data:
    name: ai_data
    driver: local

networks:
  transcendnet:
    name: transcendnet
    driver: bridge
  netplay:
    name: netplay
    driver: bridge 

  
