services:
  gameplay:
    container_name: gameplay
    build:
      context: ./web/frontend/Gameplay
      dockerfile: Dockerfile
    volumes:
      - ./web/frontend/Gameplay:/code
    ports:
      - "8081:8081"
    networks:
      - gameplay_network

networks:
  gameplay_network:
    driver: bridge 

volumes:
  gameplay_data:
    driver: local
