services:
  avago:
    image: avaplatform/subnet-evm_avalanchego:v0.7.5_v1.13.2
    container_name: avago
    ports:
      - "9650:9650"
      - "9651:9651"
    volumes:
      - ~/.avalanchego:/root/.avalanchego
    environment:
      AVAGO_PARTIAL_SYNC_PRIMARY_NETWORK: "true"
      AVAGO_PUBLIC_IP_RESOLUTION_SERVICE: "opendns"
      AVAGO_HTTP_HOST: "0.0.0.0"
      AVAGO_TRACK_SUBNETS: "29rdnbcg5c7Mvkk2YDReqUcr3Tv4WXMXxwrSV7ayWupAUaaq8A"
      AVAGO_NETWORK_ID: "fuji"
      AVAGO_HTTP_ALLOWED_HOSTS: "*"
      AVAGO_CHAIN_CONFIG_CONTENT: "eyIydFdUZmdpeHZGZkxFaU0zU3lVN2RXRXJxN0xpZHZCQXkxZ3haZHVRYUJYSzVXSkRndyI6eyJDb25maWciOiJleUp3Y25WdWFXNW5MV1Z1WVdKc1pXUWlPblJ5ZFdWOSIsIlVwZ3JhZGUiOm51bGx9fQ=="
